export const
    SET_TOKEN = "SET_TOKEN",
    SET_IS_404 = "SET_IS_404",
    SET_IS_500 = "SET_IS_500",
    SET_IS_OPEN_SIDE_BAR = "SET_IS_OPEN_SIDE_BAR",
    SET_USER_INFO = "SET_USER_INFO",
    SET_USER_BLOGS = "SET_USER_BLOGS"
